const config = {
  expressPort: 5122,
  provider: 'https://nodes.devnet.thetangle.org:443',
  seed0: 'MFDZCGQZFBYBDW9ELZVJEKQ9JTGRDMPUWHSDTQEFHIXBNRUBCYQNVGVSSEYBFWVWPCWVCECFMIEYMHRKT',
  seed1: 'BLPNHIPNLOLHWHJIIWSBTDLTLDWCCEDJWPSABSFVQRZUENBQLEKZWXZCQLQUMGQDFX9IBXAWDYIXT9JCY',
  seedCustomer: 'P9JDLEGVQHTNXLHPNAQTPHGUNZYYZHYNRFMTWMYWHFQWJWLSKATWEDTAIUEGWZMMKQMYEYRRQOSYENYMD',
};

export default config;
