const config = {
  address0: 'EYIIVLBOASB9WPIGKWQKR9XBLRULXKDDNK99PMPCK9AOBQIRVSDDFKTUWCZIAHMDLUPDEZ9XC9EYSKKR9',
  address1: 'XRUHBDGYBYQO9IXXTPTJWKQOCMKLOFUTTARNS9DJN99SAQMFKVKFFFJWCCVZS9DWQYGZNFFBCEKKFPAGD',
  expressPort: 5122,
  provider: 'https://nodes.devnet.thetangle.org:443',
  seed0: 'JVIURKOFTLBZBMGFYQUBYALHYAM99CELCQTMPQRIGTESSLYZLJGQQZIQFFGJ9SCAZCTBHWYUXLOOZJXRO',
  seed1: 'BGBLSNZFLKNXZRCXERDNSRBHMSUULSDTRPTSVPX9XOQXZZYHIIGZREGLS9VCKTKP9VBDYFZQGLHPNEKKZ',
};

export default config;
